name: UltraLogger
main: org.ultralogger.MainLogger
author: _Justyce_
manager : _Justyce_
maintener : roelmb
tester : roelmb
version: 1.6.2
description : The Ultimate logger, nothing can be done without be logged into one of the logs of this plugin. Better than Big Brother !
permissions:
  ultralogger.history:
    description: Allow players to see the history of a location in game
  ultralogger.admin:
    description: The players with this permission will be shown with the admin prefix in the logs
