name: UltraLogger
main: org.ultralogger.Main
author : _Justyce_
manager : _Justyce_
maintener : roelmb
tester : roelmb ; jamcghie
version: 2.0
description : The Ultimate logger, nothing can be done without be logged into one of the logs of this plugin. Better than Big Brother !
commands:
  /ulundo:
      description: This command undo the last block placement/break at the specified location
      usage: /<command> [x] [y] [z] [x] [y] [z]
      permission: ul.rollback
      permission-message: You don't have <permission>, you can't do this !
  /ulredo:
      description: This command restore the last block placement/break at the specified location
      usage: /<command> [x] [y] [z] [x] [y] [z]
      permission: ul.rollback
      permission-message: You don't have <permission>, you can't do this !
      
permissions:
  ul.*:
    description: Allow players to use all the features of UL ( but they will be logged )
  ul.avoid.*:
    description: Allow players not to be logged in all events 
  ul.history:
    description: Allow players to see the history of a location in game
  ul.admin:
    description: Players with this permission will be shown as Admin in the logs
  ul.rollback:
    description: Allow players to undor/redo block actions
